# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

favicon: /img/logo.svg

title: Nue Blog / A full-featured blog application

# automatically included
globals: ["@global"]
libs: ["@components", "@library"]

# globally included components
include: ["button", "interfaces", "marketing-content", "form", "card"]

# enable "turbolinking" & view transitions
view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

port: 8081

# Content collections configuration
content:
  collections:
    posts:
      directory: content/posts

navigation:
  header:
    - Nue Blog: /
    - Blog: /blog/
    - About: /about/
    - Portfolio: /portfolio/
    - Case Studies: /case-studies/
    - Contact: /contact/
    - Login: /auth/login/
    - Sign Up: /auth/signup/

  footer:
    - © Nue Blog: /

    - image: /img/twitter.svg
      url: //twitter.com/nueblog
      alt: Twitter profile
      size: 22 x 22

    - image: /img/github.svg
      url: //github.com/nuejs/nue/
      alt: Github Projects
      size: 22 x 22

    - image: /img/linkedin.svg
      url: //linkedin.com/in/nueblog
      alt: LinkedIn profile
      size: 22 x 22

