# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global"]
libs: ["@library", "@components"]

view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

title_template: "Nue Blog / %s"
og_image: /img/og_image.png
author: Nue Blog
favicon: /img/favicon.jpg
description: A full-featured blog application built with Nuejs

navigation:
  header:
    - Nue Blog: /
    - Blog: /blog/
    - About: /about/
    - Portfolio: /portfolio/
    - Case Studies: /case-studies/
    - Contact: /contact/
    - Login: /auth/login/
    - Sign Up: /auth/signup/

  footer:
    - © Nue Blog: /

    - image: /img/twitter.svg
      url: //twitter.com/nueblog
      alt: Twitter profile
      size: 22 x 22

    - image: /img/github.svg
      url: //github.com/nuejs/nue/
      alt: Github Projects
      size: 22 x 22

    - image: /img/linkedin.svg
      url: //linkedin.com/in/nueblog
      alt: LinkedIn profile
      size: 22 x 22
